// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MuseuGastronomiaCapixabaDbContext))]
    partial class MuseuGastronomiaCapixabaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Atualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ComentaristaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Desativacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceitaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Registro")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ComentaristaId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Domain.Entities.InformacaoNutricional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Atualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Desativacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("QuantidadePorcao")
                        .HasColumnType("decimal(6,3)");

                    b.Property<Guid>("ReceitaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Registro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorDiario")
                        .HasColumnType("decimal(6,3)");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("InformacoesNutricionais");
                });

            modelBuilder.Entity("Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Atualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriadorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Desativacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Historia")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<string>("ModoPreparo")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Porcao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PorcoesReceita")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Registro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UltimoEditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("UriImagem")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.HasIndex("UltimoEditorId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Atualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Desativacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Registro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("UriFotoPerfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.Comentario", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Comentarista")
                        .WithMany("Comentarios")
                        .HasForeignKey("ComentaristaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Receita", "Receita")
                        .WithMany("Comentarios")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comentarista");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("Domain.Entities.InformacaoNutricional", b =>
                {
                    b.HasOne("Domain.Entities.Receita", "Receita")
                        .WithMany("InformacoesNutricionais")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("Domain.Entities.Receita", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Criador")
                        .WithMany("ReceitasCriadas")
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Usuario", "UltimoEditor")
                        .WithMany("ReceitasEditadas")
                        .HasForeignKey("UltimoEditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criador");

                    b.Navigation("UltimoEditor");
                });

            modelBuilder.Entity("Domain.Entities.Receita", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("InformacoesNutricionais");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("ReceitasCriadas");

                    b.Navigation("ReceitasEditadas");
                });
#pragma warning restore 612, 618
        }
    }
}
